-- Generated by Level Director X v1.0.0 on Tue Dec 29 13:08:43 2015 --
require("lib.LD_HelperX")
local M={}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets={}
	assets.spriteSheetData={}
	assets.spriteSheetData['tileset']={}
	assets.spriteSheetData['tileset'].frames ={
		{x=77,y=522,width=70,height=70},
		{x=3,y=522,width=70,height=70},
		{x=373,y=521,width=70,height=70},
		{x=269,y=3,width=128,height=71},
		{x=136,y=3,width=129,height=71},
		{x=3,y=3,width=129,height=71},
		{x=299,y=448,width=70,height=70},
		{x=225,y=448,width=70,height=70},
		{x=151,y=448,width=70,height=70},
		{x=77,y=448,width=70,height=70},
		{x=3,y=448,width=70,height=70},
		{x=373,y=447,width=70,height=70},
		{x=299,y=374,width=70,height=70},
		{x=225,y=374,width=70,height=70},
		{x=151,y=374,width=70,height=70},
		{x=77,y=374,width=70,height=70},
		{x=3,y=374,width=70,height=70},
		{x=373,y=373,width=70,height=70},
		{x=299,y=300,width=70,height=70},
		{x=225,y=300,width=70,height=70},
		{x=151,y=300,width=70,height=70},
		{x=77,y=300,width=70,height=70},
		{x=3,y=300,width=70,height=70},
		{x=373,y=299,width=70,height=70},
		{x=299,y=226,width=70,height=70},
		{x=225,y=226,width=70,height=70},
		{x=484,y=3,width=5,height=24},
		{x=475,y=3,width=5,height=24},
		{x=151,y=226,width=70,height=70},
		{x=77,y=226,width=70,height=70},
		{x=3,y=226,width=70,height=70},
		{x=447,y=151,width=48,height=106},
		{x=373,y=225,width=70,height=70},
		{x=299,y=152,width=70,height=70},
		{x=225,y=152,width=70,height=70},
		{x=151,y=152,width=70,height=70},
		{x=77,y=152,width=70,height=70},
		{x=3,y=152,width=70,height=70},
		{x=373,y=151,width=70,height=70},
		{x=299,y=78,width=70,height=70},
		{x=225,y=78,width=70,height=70},
		{x=151,y=78,width=70,height=70},
		{x=77,y=78,width=70,height=70},
		{x=299,y=374,width=70,height=70},
		{x=225,y=374,width=70,height=70},
		{x=3,y=78,width=70,height=70},
		{x=401,y=77,width=70,height=70},
		{x=401,y=3,width=70,height=70},
		sheetContentWidth=512,
		sheetContentHeight=1024
	}
	assets.spriteSheetData['player']={}
	assets.spriteSheetData['player'].frames ={
		{x=0,y=0,width=48,height=48},
		{x=48,y=0,width=48,height=48},
		{x=96,y=0,width=48,height=48},
		{x=144,y=0,width=48,height=48},
		{x=0,y=48,width=48,height=48},
		{x=48,y=48,width=48,height=48},
		{x=96,y=48,width=48,height=48},
		{x=144,y=48,width=48,height=48},
		{x=0,y=96,width=48,height=48},
		{x=48,y=96,width=48,height=48},
		{x=96,y=96,width=48,height=48},
		{x=144,y=96,width=48,height=48},
		{x=0,y=144,width=48,height=48},
		{x=48,y=144,width=48,height=48},
		{x=96,y=144,width=48,height=48},
		{x=144,y=144,width=48,height=48},
		sheetContentWidth=192,
		sheetContentHeight=192
	}
	assets['bridge_png']={file ='tileset.png',name='bridge_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=1,spriteSheetName='tileset',frameCount=48,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,isBullet=false,shapes={{bodyShape='Polygon',shape={-35,15,34,14,34,34,-35,34},bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['bush_png']={file ='tileset.png',name='bush_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=2,spriteSheetName='tileset',frameCount=48,
		 }
	assets['cactus_png']={file ='tileset.png',name='cactus_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=3,spriteSheetName='tileset',frameCount=48,
		 }
	assets['cloud1_png']={file ='tileset.png',name='cloud1_png',class='',aX=0.5,aY=0.5,width=128,height=71,frame=4,spriteSheetName='tileset',frameCount=48,
		 }
	assets['cloud2_png']={file ='tileset.png',name='cloud2_png',class='',aX=0.5,aY=0.5,width=129,height=71,frame=5,spriteSheetName='tileset',frameCount=48,
		 }
	assets['cloud3_png']={file ='tileset.png',name='cloud3_png',class='',aX=0.5,aY=0.5,width=129,height=71,frame=6,spriteSheetName='tileset',frameCount=48,
		 }
	assets['fence_png']={file ='tileset.png',name='fence_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=11,spriteSheetName='tileset',frameCount=48,
		 }
	assets['grassCenter_png']={file ='tileset.png',name='grassCenter_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=13,spriteSheetName='tileset',frameCount=48,
		 }
	assets['grassCliffLeft_png']={file ='tileset.png',name='grassCliffLeft_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=15,spriteSheetName='tileset',frameCount=48,
		 }
	assets['grassCliffLeftAlt_png']={file ='tileset.png',name='grassCliffLeftAlt_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=16,spriteSheetName='tileset',frameCount=48,
		 }
	assets['grassCliffRight_png']={file ='tileset.png',name='grassCliffRight_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=17,spriteSheetName='tileset',frameCount=48,
		 }
	assets['grassCliffRightAlt_png']={file ='tileset.png',name='grassCliffRightAlt_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=18,spriteSheetName='tileset',frameCount=48,
		 }
	assets['grassHalf_png']={file ='tileset.png',name='grassHalf_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=19,spriteSheetName='tileset',frameCount=48,
		 }
	assets['grassHalfLeft_png']={file ='tileset.png',name='grassHalfLeft_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=20,spriteSheetName='tileset',frameCount=48,
		 }
	assets['grassHalfMid_png']={file ='tileset.png',name='grassHalfMid_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=21,spriteSheetName='tileset',frameCount=48,
		 }
	assets['grassHalfRight_png']={file ='tileset.png',name='grassHalfRight_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=22,spriteSheetName='tileset',frameCount=48,
		 }
	assets['grassHillLeft_png']={file ='tileset.png',name='grassHillLeft_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=23,spriteSheetName='tileset',frameCount=48,
		physics={isEnabled=true,source='Asset',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,isBullet=false,shapes={{bodyShape='Polygon',shape={35,-35,34,35,-35,34},bounce=0,friction=0,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['grassHillLeft2_png']={file ='tileset.png',name='grassHillLeft2_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=24,spriteSheetName='tileset',frameCount=48,
		 }
	assets['grassHillRight_png']={file ='tileset.png',name='grassHillRight_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=25,spriteSheetName='tileset',frameCount=48,
		 }
	assets['grassLeft_png']={file ='tileset.png',name='grassLeft_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=29,spriteSheetName='tileset',frameCount=48,
		 }
	assets['grassMid_png']={file ='tileset.png',name='grassMid_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=30,spriteSheetName='tileset',frameCount=48,
		 }
	assets['grassRight_png']={file ='tileset.png',name='grassRight_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=31,spriteSheetName='tileset',frameCount=48,
		 }
	assets['liquidWater_png']={file ='tileset.png',name='liquidWater_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=38,spriteSheetName='tileset',frameCount=48,
		 }
	assets['liquidWaterTop_png']={file ='tileset.png',name='liquidWaterTop_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=39,spriteSheetName='tileset',frameCount=48,
		 }
	assets['liquidWaterTop_mid_png']={file ='tileset.png',name='liquidWaterTop_mid_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=40,spriteSheetName='tileset',frameCount=48,
		 }
	assets['mushroomRed_png']={file ='tileset.png',name='mushroomRed_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=41,spriteSheetName='tileset',frameCount=48,
		 }
	assets['plant_png']={file ='tileset.png',name='plant_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=42,spriteSheetName='tileset',frameCount=48,
		 }
	assets['rock_png']={file ='tileset.png',name='rock_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=43,spriteSheetName='tileset',frameCount=48,
		 }
	assets['signExit_png']={file ='tileset.png',name='signExit_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=46,spriteSheetName='tileset',frameCount=48,
		 }
	assets['signRight_png']={file ='tileset.png',name='signRight_png',class='',aX=0.5,aY=0.5,width=70,height=70,frame=47,spriteSheetName='tileset',frameCount=48,
		 }
	assets['star_png']={file ='tileset.png',name='star_png',class='Star',aX=0.5,aY=0.5,width=70,height=70,frame=48,spriteSheetName='tileset',frameCount=48,
		physics={isEnabled=true,source='Asset',bodyType='kinematic',isFixedRotation=false,isSleepingAllowed=false,isSensor=true,isBullet=false,shapes={{bodyShape='Round',shape={},bounce=0,friction=0,density=1,radius=17,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	assets['bg_0']={file ='bg.png',name='bg_0',class='',aX=0.5,aY=0.5,width=256,height=256,frame=0,spriteSheetName='bg',frameCount=1,
		 }
	assets['player_0']={file ='player.png',name='player_0',class='',aX=0.5,aY=0.5,width=48,height=48,frame=1,spriteSheetName='player',frameCount=16,
		sequenceData={{name='down',frames={ 1,5,9,13 },time =500,loopCount=0,loopDirection='forward' },{name='left',frames={ 2,6,10,14 },time =500,loopCount=0,loopDirection='forward' },{name='up',frames={ 1 },time =500,loopCount=1,loopDirection='forward' },{name='right',frames={ 4,8,12,16 },time =500,loopCount=0,loopDirection='forward' },},
		sequenceInfo={default='',play=false },
		physics={isEnabled=true,source='Asset',bodyType='dynamic',isFixedRotation=true,isSleepingAllowed=false,isSensor=false,isBullet=false,shapes={{bodyShape='Round',shape={},bounce=0.1,friction=0.23,density=0.8,radius=18,categoryBits=0,maskBits=0,groupIndex=0},}	}  }
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance=LD_Helper_Instance
	local objProps={}
	local level={}
    local obj=nil
	if (instance.viewGroup == nil) then
		level.view=display.newGroup() 
	else
		level.view=instance.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',0/255,85/255,0/255,255/255)
	display.setDefault( "anchorX",0.5 )
	display.setDefault( "anchorY",0.5 )	
	display.setDrawMode("wireframe",false)
	level.name='Level01' 
	-- Load Assets
	level.assets=self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled=true
	level.Star=''
	-- Layers --
	level.layers={} 
	---- sky ------------------------------------------------------------------------------------
	level.layers['sky']={} 
	level.layers['sky'].view=display.newGroup() 
	level.layers['sky'].name='sky' 
	if (level.parallaxEnabled) then
		level.layers['sky'].speed={x=0,y=0}
		level.layers['sky'].repeated=false
		level.layers['sky'].cullingMethod=0
	else
		level.layers['sky'].cullingMethod=0 
	end
	level.layers['sky'].objects={} 
	objProps={name='bg_0',objType='LDImage',class='',width=1136,height=1200,x=568,y=600,xScale=4.4375*1,yScale=4.6875*1,assetName='bg_0',
}	
	obj=instance:createObject(level.layers['sky'],objProps,level.assets) 
	instance:insertLayer(level,level.layers['sky'])
	---- Clouds ------------------------------------------------------------------------------------
	level.layers['Clouds']={} 
	level.layers['Clouds'].view=display.newGroup() 
	level.layers['Clouds'].name='Clouds' 
	if (level.parallaxEnabled) then
		level.layers['Clouds'].speed={x=0.1,y=0.1}
		level.layers['Clouds'].repeated=false
		level.layers['Clouds'].cullingMethod=0
	else
		level.layers['Clouds'].cullingMethod=0 
	end
	level.layers['Clouds'].objects={} 
	objProps={name='cloud1_png',objType='LDImage',class='',width=256,height=112,x=208,y=152,xScale=2*1,yScale=1.57746*1,assetName='cloud1_png',
}	
	obj=instance:createObject(level.layers['Clouds'],objProps,level.assets) 
	objProps={name='cloud2_png',objType='LDImage',class='',width=208,height=96,x=360,y=208,xScale=1.6124*1,yScale=1.35211*1,assetName='cloud2_png',
}	
	obj=instance:createObject(level.layers['Clouds'],objProps,level.assets) 
	objProps={name='cloud3_png',objType='LDImage',class='',width=129,height=71,x=144,y=211,xScale=1*1,yScale=1*1,assetName='cloud3_png',
}	
	obj=instance:createObject(level.layers['Clouds'],objProps,level.assets) 
	objProps={name='cloud3_png',objType='LDImage',class='',width=129,height=71,x=864,y=131,xScale=1*1,yScale=1*1,assetName='cloud3_png',
}	
	obj=instance:createObject(level.layers['Clouds'],objProps,level.assets) 
	objProps={name='cloud1_png',objType='LDImage',class='',width=288,height=112,x=864,y=184,xScale=2.25*1,yScale=1.57746*1,assetName='cloud1_png',
}	
	obj=instance:createObject(level.layers['Clouds'],objProps,level.assets) 
	objProps={name='cloud2_png',objType='LDImage',class='',width=224,height=144,x=592,y=136,xScale=1.73643*1,yScale=2.02817*1,assetName='cloud2_png',
}	
	obj=instance:createObject(level.layers['Clouds'],objProps,level.assets) 
	objProps={name='cloud3_png',objType='LDImage',class='',width=129,height=71,x=1168,y=51,xScale=1*1,yScale=1*1,assetName='cloud3_png',
}	
	obj=instance:createObject(level.layers['Clouds'],objProps,level.assets) 
	objProps={name='cloud2_png',objType='LDImage',class='',width=129,height=71,x=1376,y=147,xScale=1*1,yScale=1*1,assetName='cloud2_png',
}	
	obj=instance:createObject(level.layers['Clouds'],objProps,level.assets) 
	instance:insertLayer(level,level.layers['Clouds'])
	---- BG ------------------------------------------------------------------------------------
	level.layers['BG']={} 
	level.layers['BG'].view=display.newGroup() 
	level.layers['BG'].name='BG' 
	if (level.parallaxEnabled) then
		level.layers['BG'].speed={x=1,y=1}
		level.layers['BG'].repeated=false
		level.layers['BG'].cullingMethod=0
	else
		level.layers['BG'].cullingMethod=0 
	end
	level.layers['BG'].objects={} 
	objProps={name='liquidWater_png',objType='LDImage',class='',width=70,height=70,x=1990,y=676,xScale=1*1,yScale=1*1,assetName='liquidWater_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='liquidWater_png',objType='LDImage',class='',width=70,height=70,x=1712,y=676,xScale=1*1,yScale=1*1,assetName='liquidWater_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='liquidWaterTop_png',objType='LDImage',class='',width=70,height=70,x=1986,y=612,xScale=1*1,yScale=1*1,assetName='liquidWaterTop_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='liquidWaterTop_png',objType='LDImage',class='',width=70,height=70,x=1707,y=612,xScale=1*1,yScale=1*1,assetName='liquidWaterTop_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=107,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=177,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=247,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=317,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHillLeft_png',objType='LDImage',class='',width=70,height=70,x=387,y=536,xScale=1*1,yScale=1*1,assetName='grassHillLeft_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHillLeft2_png',objType='LDImage',class='',width=70,height=70,x=387,y=606,xScale=1*1,yScale=1*1,assetName='grassHillLeft2_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=457,y=536,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=526,y=536,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHillLeft_png',objType='LDImage',class='',width=70,height=70,x=595,y=466,xScale=1*1,yScale=1*1,assetName='grassHillLeft_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHillLeft2_png',objType='LDImage',class='',width=70,height=70,x=595,y=536,xScale=1*1,yScale=1*1,assetName='grassHillLeft2_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=456,y=606,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=526,y=606,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=595,y=606,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=665,y=466,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCliffRightAlt_png',objType='LDImage',class='',width=70,height=70,x=735,y=466,xScale=1*1,yScale=1*1,assetName='grassCliffRightAlt_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCliffRight_png',objType='LDImage',class='',width=70,height=70,x=665,y=606,xScale=1*1,yScale=1*1,assetName='grassCliffRight_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=665,y=536,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=665,y=606,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=735,y=606,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=805,y=606,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=805,y=536,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=735,y=536,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=1155,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=1085,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=1015,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=945,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=875,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCliffRight_png',objType='LDImage',class='',width=70,height=70,x=874,y=536,xScale=1*1,yScale=1*1,assetName='grassCliffRight_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHalf_png',objType='LDImage',class='',width=70,height=70,x=317,y=412,xScale=1*1,yScale=1*1,assetName='grassHalf_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHalfRight_png',objType='LDImage',class='',width=70,height=70,x=216,y=508,xScale=1*1,yScale=1*1,assetName='grassHalfRight_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHalfLeft_png',objType='LDImage',class='',width=70,height=70,x=147,y=508,xScale=1*1,yScale=1*1,assetName='grassHalfLeft_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=1225,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=1295,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=1365,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCliffLeftAlt_png',objType='LDImage',class='',width=70,height=70,x=1365,y=536,xScale=1*1,yScale=1*1,assetName='grassCliffLeftAlt_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=1435,y=606,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=1435,y=536,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHalfLeft_png',objType='LDImage',class='',width=70,height=70,x=866,y=411,xScale=1*1,yScale=1*1,assetName='grassHalfLeft_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHalfRight_png',objType='LDImage',class='',width=70,height=70,x=935,y=411,xScale=1*1,yScale=1*1,assetName='grassHalfRight_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHalfLeft_png',objType='LDImage',class='',width=70,height=70,x=1038,y=343,xScale=1*1,yScale=1*1,assetName='grassHalfLeft_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHalfRight_png',objType='LDImage',class='',width=70,height=70,x=1107,y=343,xScale=1*1,yScale=1*1,assetName='grassHalfRight_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHalfLeft_png',objType='LDImage',class='',width=70,height=70,x=1531,y=439,xScale=1*1,yScale=1*1,assetName='grassHalfLeft_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHalfRight_png',objType='LDImage',class='',width=70,height=70,x=1600,y=439,xScale=1*1,yScale=1*1,assetName='grassHalfRight_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=1504,y=606,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=1574,y=606,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCliffRightAlt_png',objType='LDImage',class='',width=70,height=70,x=1504,y=536,xScale=1*1,yScale=1*1,assetName='grassCliffRightAlt_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHalfLeft_png',objType='LDImage',class='',width=70,height=70,x=1504,y=579,xScale=1*1,yScale=1*1,assetName='grassHalfLeft_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=1642,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHalfRight_png',objType='LDImage',class='',width=70,height=70,x=1574,y=579,xScale=1*1,yScale=1*1,assetName='grassHalfRight_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='signRight_png',objType='LDImage',class='',width=70,height=70,x=46,y=537,xScale=1*1,yScale=1*1,assetName='signRight_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='rect_51',objType='LDRectangle',class='',width=1679,height=39,x=842,y=591,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=839.5,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		physics={isEnabled=true,source='Object',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,isBullet=false,gravityScale=1,
		shapes={{bodyShape='Rectangle',shape={ },bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0 },}}
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='rect_3',objType='LDRectangle',class='',width=139,height=31,x=699,y=446,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=69.5,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		physics={isEnabled=true,source='Object',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,isBullet=false,gravityScale=1,
		shapes={{bodyShape='Rectangle',shape={ },bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0 },}}
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='rect_4',objType='LDRectangle',class='',width=488,height=33,x=666,y=517,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=244,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		physics={isEnabled=true,source='Object',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,isBullet=false,gravityScale=1,
		shapes={{bodyShape='Rectangle',shape={ },bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0 },}}
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='rect_6',objType='LDRectangle',class='',width=208,height=29,x=1435,y=515,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=104,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		physics={isEnabled=true,source='Object',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,isBullet=false,gravityScale=1,
		shapes={{bodyShape='Rectangle',shape={ },bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0 },}}
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='rect_7',objType='LDRectangle',class='',width=138,height=26,x=1539,y=558,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=69,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		physics={isEnabled=true,source='Object',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,isBullet=false,gravityScale=1,
		shapes={{bodyShape='Rectangle',shape={ },bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0 },}}
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='rect_8',objType='LDRectangle',class='',width=138,height=24,x=1566,y=416,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=69,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		physics={isEnabled=true,source='Object',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,isBullet=false,gravityScale=1,
		shapes={{bodyShape='Rectangle',shape={ },bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0 },}}
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='rect_8',objType='LDRectangle',class='',width=138,height=24,x=1073,y=321,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=69,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=253/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		physics={isEnabled=true,source='Object',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,isBullet=false,gravityScale=1,
		shapes={{bodyShape='Rectangle',shape={ },bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0 },}}
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='rect_8',objType='LDRectangle',class='',width=138,height=24,x=901,y=388,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=69,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=253/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		physics={isEnabled=true,source='Object',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,isBullet=false,gravityScale=1,
		shapes={{bodyShape='Rectangle',shape={ },bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0 },}}
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='rect_8',objType='LDRectangle',class='',width=138,height=24,x=182,y=486,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=69,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		physics={isEnabled=true,source='Object',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,isBullet=false,gravityScale=1,
		shapes={{bodyShape='Rectangle',shape={ },bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0 },}}
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='rect_8',objType='LDRectangle',class='',width=69,height=24,x=316,y=390,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=34.5,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		physics={isEnabled=true,source='Object',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,isBullet=false,gravityScale=1,
		shapes={{bodyShape='Rectangle',shape={ },bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0 },}}
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='liquidWaterTop_mid_png',objType='LDImage',class='',width=70,height=70,x=1777,y=612,xScale=1*1,yScale=1*1,assetName='liquidWaterTop_mid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='liquidWaterTop_png',objType='LDImage',class='',width=70,height=70,x=1847,y=612,xScale=1*1,yScale=1*1,assetName='liquidWaterTop_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='liquidWaterTop_mid_png',objType='LDImage',class='',width=70,height=70,x=1916,y=612,xScale=1*1,yScale=1*1,assetName='liquidWaterTop_mid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='bridge_png',objType='LDImage',class='',width=70,height=70,x=1714,y=556,xScale=1*1,yScale=1*1,assetName='bridge_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='bridge_png',objType='LDImage',class='',width=70,height=70,x=1785,y=556,xScale=1*1,yScale=1*1,assetName='bridge_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='bridge_png',objType='LDImage',class='',width=70,height=70,x=1856,y=556,xScale=1*1,yScale=1*1,assetName='bridge_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='bridge_png',objType='LDImage',class='',width=70,height=70,x=1927,y=556,xScale=1*1,yScale=1*1,assetName='bridge_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=2204,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=2066,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=2273,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=2135,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassLeft_png',objType='LDImage',class='',width=70,height=70,x=1997,y=606,xScale=1*1,yScale=1*1,assetName='grassLeft_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=2478,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=2410,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=2342,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=2753,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=2546,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=2684,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=2615,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassRight_png',objType='LDImage',class='',width=70,height=70,x=2844,y=606,xScale=1*1,yScale=1*1,assetName='grassRight_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='signExit_png',objType='LDImage',class='',width=70,height=70,x=2824,y=536,xScale=1*1,yScale=1*1,assetName='signExit_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHalfRight_png',objType='LDImage',class='',width=70,height=70,x=1974,y=479,xScale=1*1,yScale=1*1,assetName='grassHalfRight_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHalfLeft_png',objType='LDImage',class='',width=70,height=70,x=1905,y=479,xScale=1*1,yScale=1*1,assetName='grassHalfLeft_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHalfRight_png',objType='LDImage',class='',width=70,height=70,x=1801,y=318,xScale=1*1,yScale=1*1,assetName='grassHalfRight_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHalfLeft_png',objType='LDImage',class='',width=70,height=70,x=1732,y=318,xScale=1*1,yScale=1*1,assetName='grassHalfLeft_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHalfRight_png',objType='LDImage',class='',width=70,height=70,x=2044,y=243,xScale=1*1,yScale=1*1,assetName='grassHalfRight_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHalfLeft_png',objType='LDImage',class='',width=70,height=70,x=1975,y=243,xScale=1*1,yScale=1*1,assetName='grassHalfLeft_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHalfRight_png',objType='LDImage',class='',width=70,height=70,x=2227,y=396,xScale=1*1,yScale=1*1,assetName='grassHalfRight_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHalfLeft_png',objType='LDImage',class='',width=70,height=70,x=2158,y=396,xScale=1*1,yScale=1*1,assetName='grassHalfLeft_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHalfRight_png',objType='LDImage',class='',width=70,height=70,x=2486,y=304,xScale=1*1,yScale=1*1,assetName='grassHalfRight_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHalfLeft_png',objType='LDImage',class='',width=70,height=70,x=2417,y=304,xScale=1*1,yScale=1*1,assetName='grassHalfLeft_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='rect_8',objType='LDRectangle',class='',width=138,height=24,x=1767,y=295,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=69,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		physics={isEnabled=true,source='Object',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,isBullet=false,gravityScale=1,
		shapes={{bodyShape='Rectangle',shape={ },bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0 },}}
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='rect_8',objType='LDRectangle',class='',width=138,height=24,x=2010,y=220,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=69,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		physics={isEnabled=true,source='Object',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,isBullet=false,gravityScale=1,
		shapes={{bodyShape='Rectangle',shape={ },bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0 },}}
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='rect_8',objType='LDRectangle',class='',width=138,height=24,x=2193,y=373,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=69,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		physics={isEnabled=true,source='Object',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,isBullet=false,gravityScale=1,
		shapes={{bodyShape='Rectangle',shape={ },bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0 },}}
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='rect_8',objType='LDRectangle',class='',width=138,height=24,x=1940,y=456,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=69,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		physics={isEnabled=true,source='Object',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,isBullet=false,gravityScale=1,
		shapes={{bodyShape='Rectangle',shape={ },bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0 },}}
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='rect_8',objType='LDRectangle',class='',width=138,height=24,x=2452,y=281,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=69,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		physics={isEnabled=true,source='Object',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,isBullet=false,gravityScale=1,
		shapes={{bodyShape='Rectangle',shape={ },bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0 },}}
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassHalf_png',objType='LDImage',class='',width=70,height=70,x=1443,y=294,xScale=1*1,yScale=1*1,assetName='grassHalf_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='rect_8',objType='LDRectangle',class='',width=69,height=24,x=1442,y=272,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=34.5,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		physics={isEnabled=true,source='Object',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,isBullet=false,gravityScale=1,
		shapes={{bodyShape='Rectangle',shape={ },bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0 },}}
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=107,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=177,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=386,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=246,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=316,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCliffLeft_png',objType='LDImage',class='',width=70,height=70,x=37,y=606,xScale=1*1,yScale=1*1,assetName='grassCliffLeft_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=526,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=595,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=665,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=735,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=456,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=875,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=944,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=1014,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=1084,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=805,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=1224,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=1293,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=1363,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=1433,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=1154,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=1573,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=1642,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=1503,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=1997,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=2067,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=2135,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=2273,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=2342,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=2411,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=2480,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=2204,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=2618,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=2686,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=2754,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=2824,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassCenter_png',objType='LDImage',class='',width=70,height=70,x=2549,y=676,xScale=1*1,yScale=1*1,assetName='grassCenter_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='liquidWater_png',objType='LDImage',class='',width=70,height=70,x=1781,y=676,xScale=1*1,yScale=1*1,assetName='liquidWater_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='liquidWater_png',objType='LDImage',class='',width=70,height=70,x=1851,y=676,xScale=1*1,yScale=1*1,assetName='liquidWater_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='liquidWater_png',objType='LDImage',class='',width=70,height=70,x=1920,y=676,xScale=1*1,yScale=1*1,assetName='liquidWater_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='grassMid_png',objType='LDImage',class='',width=70,height=70,x=2822,y=606,xScale=1*1,yScale=1*1,assetName='grassMid_png',
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	objProps={name='rect_85',objType='LDRectangle',class='',width=933,height=36,x=2426,y=589,xScale=1*1,yScale=1*1,assetName='',
		styleProps={radius=466.5,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=0/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		physics={isEnabled=true,source='Object',bodyType='static',isFixedRotation=false,isSleepingAllowed=false,isSensor=false,isBullet=false,gravityScale=1,
		shapes={{bodyShape='Rectangle',shape={ },bounce=0.2,friction=0.3,density=1,radius=0,categoryBits=0,maskBits=0,groupIndex=0 },}}
}	
	obj=instance:createObject(level.layers['BG'],objProps,level.assets) 
	instance:insertLayer(level,level.layers['BG'])
	---- Player ------------------------------------------------------------------------------------
	level.layers['Player']={} 
	level.layers['Player'].view=display.newGroup() 
	level.layers['Player'].name='Player' 
	if (level.parallaxEnabled) then
		level.layers['Player'].speed={x=1,y=1}
		level.layers['Player'].repeated=false
		level.layers['Player'].cullingMethod=0
	else
		level.layers['Player'].cullingMethod=0 
	end
	level.layers['Player'].objects={} 
	objProps={name='player',objType='LDImage',class='',width=64,height=64,x=496,y=368,xScale=1.33333*1,yScale=1.33333*1,assetName='player_0',
}	
	obj=instance:createObject(level.layers['Player'],objProps,level.assets) 
	instance:insertLayer(level,level.layers['Player'])
	---- FG ------------------------------------------------------------------------------------
	level.layers['FG']={} 
	level.layers['FG'].view=display.newGroup() 
	level.layers['FG'].name='FG' 
	if (level.parallaxEnabled) then
		level.layers['FG'].speed={x=1,y=1}
		level.layers['FG'].repeated=false
		level.layers['FG'].cullingMethod=0
	else
		level.layers['FG'].cullingMethod=0 
	end
	level.layers['FG'].objects={} 
	objProps={name='fence_png',objType='LDImage',class='',width=70,height=70,x=1081,y=538,xScale=1*1,yScale=1*1,assetName='fence_png',
}	
	obj=instance:createObject(level.layers['FG'],objProps,level.assets) 
	objProps={name='fence_png',objType='LDImage',class='',width=70,height=70,x=1152,y=538,xScale=1*1,yScale=1*1,assetName='fence_png',
}	
	obj=instance:createObject(level.layers['FG'],objProps,level.assets) 
	objProps={name='fence_png',objType='LDImage',class='',width=70,height=70,x=1223,y=538,xScale=1*1,yScale=1*1,assetName='fence_png',
}	
	obj=instance:createObject(level.layers['FG'],objProps,level.assets) 
	objProps={name='mushroomRed_png',objType='LDImage',class='',width=70,height=70,x=1371,y=466,xScale=1*1,yScale=1*1,assetName='mushroomRed_png',
}	
	obj=instance:createObject(level.layers['FG'],objProps,level.assets) 
	objProps={name='cactus_png',objType='LDImage',class='',width=70,height=70,x=679,y=397,xScale=1*1,yScale=1*1,assetName='cactus_png',
}	
	obj=instance:createObject(level.layers['FG'],objProps,level.assets) 
	objProps={name='bush_png',objType='LDImage',class='',width=70,height=70,x=2140,y=538,xScale=1*1,yScale=1*1,assetName='bush_png',
}	
	obj=instance:createObject(level.layers['FG'],objProps,level.assets) 
	objProps={name='plant_png',objType='LDImage',class='',width=70,height=70,x=291,y=538,xScale=1*1,yScale=1*1,assetName='plant_png',
}	
	obj=instance:createObject(level.layers['FG'],objProps,level.assets) 
	objProps={name='rock_png',objType='LDImage',class='',width=70,height=70,x=2393,y=538,xScale=1*1,yScale=1*1,assetName='rock_png',
}	
	obj=instance:createObject(level.layers['FG'],objProps,level.assets) 
	objProps={name='plant_png',objType='LDImage',class='',width=70,height=70,x=2185,y=327,xScale=1*1,yScale=1*1,assetName='plant_png',
}	
	obj=instance:createObject(level.layers['FG'],objProps,level.assets) 
	objProps={name='plant_png',objType='LDImage',class='',width=70,height=70,x=2362,y=538,xScale=1*1,yScale=1*1,assetName='plant_png',
}	
	obj=instance:createObject(level.layers['FG'],objProps,level.assets) 
	objProps={name='star1',objType='LDImage',class='Star',width=70,height=70,x=2011,y=97,xScale=1*1,yScale=1*1,assetName='star_png',
}	
	obj=instance:createObject(level.layers['FG'],objProps,level.assets) 
	objProps={name='star2',objType='LDImage',class='Star',width=70,height=70,x=2454,y=183,xScale=1*1,yScale=1*1,assetName='star_png',
}	
	obj=instance:createObject(level.layers['FG'],objProps,level.assets) 
	objProps={name='star3',objType='LDImage',class='Star',width=70,height=70,x=185,y=326,xScale=1*1,yScale=1*1,assetName='star_png',
}	
	obj=instance:createObject(level.layers['FG'],objProps,level.assets) 
	objProps={name='star4',objType='LDImage',class='Star',width=70,height=70,x=894,y=213,xScale=1*1,yScale=1*1,assetName='star_png',
}	
	obj=instance:createObject(level.layers['FG'],objProps,level.assets) 
	objProps={name='star5',objType='LDImage',class='Star',width=70,height=70,x=1437,y=131,xScale=1*1,yScale=1*1,assetName='star_png',
}	
	obj=instance:createObject(level.layers['FG'],objProps,level.assets) 
	objProps={name='star6',objType='LDImage',class='Star',width=70,height=70,x=2660,y=345,xScale=1*1,yScale=1*1,assetName='star_png',
}	
	obj=instance:createObject(level.layers['FG'],objProps,level.assets) 
	objProps={name='star7',objType='LDImage',class='Star',width=70,height=70,x=2206,y=255,xScale=1*1,yScale=1*1,assetName='star_png',
}	
	obj=instance:createObject(level.layers['FG'],objProps,level.assets) 
	objProps={name='star8',objType='LDImage',class='Star',width=70,height=70,x=1751,y=520,xScale=1*1,yScale=1*1,assetName='star_png',
}	
	obj=instance:createObject(level.layers['FG'],objProps,level.assets) 
	objProps={name='star9',objType='LDImage',class='Star',width=70,height=70,x=483,y=296,xScale=1*1,yScale=1*1,assetName='star_png',
}	
	obj=instance:createObject(level.layers['FG'],objProps,level.assets) 
	objProps={name='star10',objType='LDImage',class='Star',width=70,height=70,x=1429,y=446,xScale=1*1,yScale=1*1,assetName='star_png',
}	
	obj=instance:createObject(level.layers['FG'],objProps,level.assets) 
	objProps={name='plant_png',objType='LDImage',class='',width=70,height=70,x=2424,y=538,xScale=1*-1,yScale=1*1,assetName='plant_png',
}	
	obj=instance:createObject(level.layers['FG'],objProps,level.assets) 
	objProps={name='fence_png',objType='LDImage',class='',width=70,height=70,x=1010,y=538,xScale=1*1,yScale=1*1,assetName='fence_png',
}	
	obj=instance:createObject(level.layers['FG'],objProps,level.assets) 
	instance:insertLayer(level,level.layers['FG'])
	---- Markers ------------------------------------------------------------------------------------
	level.layers['Markers']={} 
	level.layers['Markers'].view=display.newGroup() 
	level.layers['Markers'].name='Markers' 
	if (level.parallaxEnabled) then
		level.layers['Markers'].speed={x=0,y=0}
		level.layers['Markers'].repeated=false
		level.layers['Markers'].cullingMethod=0
	else
		level.layers['Markers'].cullingMethod=0 
	end
	level.layers['Markers'].objects={} 
	objProps={name='marker_2',objType='LDMarker',class='',width=32,height=32,x=1922,y=0,xScale=1*1,yScale=1*1,assetName='',
		rotation=0,enableDrag=false,anchorX=0,anchorY=0,alpha=1,isVisible=true,blendMode='normal',
}	
	obj=instance:createObject(level.layers['Markers'],objProps,level.assets) 
	objProps={name='marker_1',objType='LDMarker',class='',width=32,height=32,x=0,y=0,xScale=1*1,yScale=1*1,assetName='',
		rotation=0,enableDrag=false,anchorX=0,anchorY=0,alpha=1,isVisible=true,blendMode='normal',
}	
	obj=instance:createObject(level.layers['Markers'],objProps,level.assets) 
	instance:insertLayer(level,level.layers['Markers'])
	---- Controls ------------------------------------------------------------------------------------
	level.layers['Controls']={} 
	level.layers['Controls'].view=display.newGroup() 
	level.layers['Controls'].name='Controls' 
	if (level.parallaxEnabled) then
		level.layers['Controls'].speed={x=0,y=0}
		level.layers['Controls'].repeated=false
		level.layers['Controls'].cullingMethod=0
	else
		level.layers['Controls'].cullingMethod=0 
	end
	level.layers['Controls'].objects={} 
	objProps={name='btnLeft',objType='LDButton',class='',width=50,height=50,x=38,y=607,xScale=1*1,yScale=1*1,assetName='',
		textProps={text='L',font='Arial',size=18,embossed=false,embossHighlightColorR=255/255,embossHighlightColorG=255/255,embossHighlightColorB=255/255,embossHighlightColorA=255/255,embossShadowColorR=255/255,embossShadowColorG=255/255,embossShadowColorB=255/255,embossShadowColorA=255/255},
		styleProps={radius=25,cornerRadius=10,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=100/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=100/255},
		btnProps={textColorR=255/255,textColorG=255/255,textColorB=255/255,textColorA=255/255,fillType=0,fillAssetName='',fillFrame=0,styleProps	= {cornerRadius=10,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=100/255,fillColorG=0/255,fillColorB=0/255,fillColorA=200/255}},
}	
	obj=instance:createObject(level.layers['Controls'],objProps,level.assets) 
	objProps={name='btnRight',objType='LDButton',class='',width=50,height=50,x=100,y=607,xScale=1*1,yScale=1*1,assetName='',
		textProps={text='R',font='Arial',size=18,embossed=false,embossHighlightColorR=255/255,embossHighlightColorG=255/255,embossHighlightColorB=255/255,embossHighlightColorA=255/255,embossShadowColorR=255/255,embossShadowColorG=255/255,embossShadowColorB=255/255,embossShadowColorA=255/255},
		styleProps={radius=25,cornerRadius=10,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=100/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=100/255},
		btnProps={textColorR=255/255,textColorG=255/255,textColorB=255/255,textColorA=255/255,fillType=0,fillAssetName='',fillFrame=0,styleProps	= {cornerRadius=10,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=100/255,fillColorG=0/255,fillColorB=0/255,fillColorA=200/255}},
}	
	obj=instance:createObject(level.layers['Controls'],objProps,level.assets) 
	objProps={name='btnUp',objType='LDButton',class='',width=50,height=50,x=918,y=607,xScale=1*1,yScale=1*1,assetName='',
		textProps={text='J',font='Arial',size=18,embossed=false,embossHighlightColorR=255/255,embossHighlightColorG=255/255,embossHighlightColorB=255/255,embossHighlightColorA=255/255,embossShadowColorR=255/255,embossShadowColorG=255/255,embossShadowColorB=255/255,embossShadowColorA=255/255},
		styleProps={radius=25,cornerRadius=10,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=100/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=100/255},
		btnProps={textColorR=255/255,textColorG=255/255,textColorB=255/255,textColorA=255/255,fillType=0,fillAssetName='',fillFrame=0,styleProps	= {cornerRadius=10,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=100/255,fillColorG=0/255,fillColorB=0/255,fillColorA=200/255}},
}	
	obj=instance:createObject(level.layers['Controls'],objProps,level.assets) 
	objProps={name='coords',objType='LDText',class='',width=33,height=27,x=497,y=586,xScale=1*1,yScale=1*1,assetName='',
		rotation=0,enableDrag=false,anchorX=0,anchorY=0,alpha=1,isVisible=true,blendMode='normal',
		textProps={text='0,0',font='Arial',size=22,embossed=false,embossHighlightColorR=255/255,embossHighlightColorG=255/255,embossHighlightColorB=255/255,embossHighlightColorA=255/255,embossShadowColorR=255/255,embossShadowColorG=255/255,embossShadowColorB=255/255,embossShadowColorA=255/255},
		styleProps={radius=16.5,cornerRadius=0,strokeWidth=1,strokeColorR=255/255,strokeColorG=255/255,strokeColorB=255/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
}	
	obj=instance:createObject(level.layers['Controls'],objProps,level.assets) 
	objProps={name='demo',objType='LDText',class='',width=615,height=30,x=212,y=23,xScale=1*1,yScale=1*1,assetName='',
		rotation=0,enableDrag=false,anchorX=0,anchorY=0,alpha=1,isVisible=true,blendMode='normal',
		textProps={text='Level Director X Demo - www.retrofitproductions.com',font='Arial Black',size=20,embossed=true,embossHighlightColorR=255/255,embossHighlightColorG=255/255,embossHighlightColorB=255/255,embossHighlightColorA=255/255,embossShadowColorR=255/255,embossShadowColorG=255/255,embossShadowColorB=255/255,embossShadowColorA=255/255},
		styleProps={radius=307.5,cornerRadius=0,strokeWidth=1,strokeColorR=0/255,strokeColorG=0/255,strokeColorB=127/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
}	
	obj=instance:createObject(level.layers['Controls'],objProps,level.assets) 
	objProps={name='score',objType='LDText',class='',width=23,height=27,x=884,y=30,xScale=1*1,yScale=1*1,assetName='',
		rotation=0,enableDrag=false,anchorX=0,anchorY=0,alpha=1,isVisible=true,blendMode='normal',
		textProps={text='0',font='Arial',size=22,embossed=false,embossHighlightColorR=255/255,embossHighlightColorG=255/255,embossHighlightColorB=255/255,embossHighlightColorA=255/255,embossShadowColorR=255/255,embossShadowColorG=255/255,embossShadowColorB=255/255,embossShadowColorA=255/255},
		styleProps={radius=11.5,cornerRadius=0,strokeWidth=1,strokeColorR=0/255,strokeColorG=0/255,strokeColorB=127/255,strokeColorA=255/255,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
		fillProps ={fillType=0,fillAssetName='',fillFrame=0},
		gradientProps={direction=0,fillColorR=0/255,fillColorG=0/255,fillColorB=0/255,fillColorA=0/255},
}	
	obj=instance:createObject(level.layers['Controls'],objProps,level.assets) 
	instance:insertLayer(level,level.layers['Controls'])
	--level.ldVersion=1.0.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth=2880
	level.canvasHeight=640
	if level.parallaxEnabled then
		level.parallaxInfinite=true
		level.parallaxDamping=1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

