-- Generated by Level Director X v1.0.0 on Wed Jul 29 13:47:06 2015 --
require("lib.LD_HelperX")
local M = {}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets = {}
	assets.spriteSheetData = {}
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance = LD_Helper_Instance
	local objProps = {}
	local level = {}
    local obj = nil
	if (application.LevelDirectorSettings.viewGroup == nil) then
		level.view = display.newGroup() 
	else
		level.view = application.LevelDirectorSettings.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',  128 / 255, 128 / 255, 128 / 255, 255 / 255)
	display.setDefault( "anchorX", 0.5 )
	display.setDefault( "anchorY", 0.5 )	
	display.setDrawMode("wireframe",false)
	level.name = 'Level01' 
	-- Load Assets
	level.assets = self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('normal')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled = false
	-- Layers --
	level.layers = {} 
	---- Layer1 ------------------------------------------------------------------------------------
	level.layers['Layer1'] = {} 
	level.layers['Layer1'].view = display.newGroup() 
	level.layers['Layer1'].name = 'Layer1' 
	if (level.parallaxEnabled) then
		level.layers['Layer1'].speed = {x = 0, y = 0}
		level.layers['Layer1'].repeated = false
		level.layers['Layer1'].cullingMethod = 0
	else
		level.layers['Layer1'].cullingMethod = 0 
	end
	level.layers['Layer1'].objects = {} 
	objProps = 
	{
		name 	= 'left_eye', 
		objType = 'LDEllipse',
		class = '',
		width	= 160,
		height	= 160,
		x		= 176,
		y		= 256,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		assetName	= '',
		styleProps	= {radius = 80, cornerRadius = 0,strokeWidth = 1, strokeColorR = 255 / 255,strokeColorG = 255 / 255,strokeColorB = 255 / 255, strokeColorA = 255 / 255, fillColorR = 0 / 255, fillColorG = 0 / 255, fillColorB = 0 / 255, fillColorA = 0 / 255},
		fillProps = {fillType = 0, fillAssetName = '', fillFrame = 0 },
		gradientProps = {direction = 0, fillColorR = 0 / 255,fillColorG = 0 / 255,fillColorB = 0 / 255, fillColorA = 0 / 255},
		}
	obj = instance:createObject(level.layers['Layer1'],objProps, level.assets) 
	objProps = 
	{
		name 	= 'lips', 
		objType = 'LDPolygon',
		class = '',
		width	= 0,
		height	= 0,
		x		= 320,
		y		= 616,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		assetName	= '',
		styleProps	= {radius = 0, cornerRadius = 0,strokeWidth = 1, strokeColorR = 255 / 255,strokeColorG = 255 / 255,strokeColorB = 255 / 255, strokeColorA = 255 / 255, fillColorR = 0 / 255, fillColorG = 0 / 255, fillColorB = 0 / 255, fillColorA = 0 / 255},
		fillProps = {fillType = 0, fillAssetName = '', fillFrame = 0 },
		gradientProps = {direction = 0, fillColorR = 0 / 255,fillColorG = 0 / 255,fillColorB = 0 / 255, fillColorA = 0 / 255},
		pointProps = {outputType = 'Display', xPoints = {0,256,256,0,-256,-256}, yPoints = { -120,-24,24,120,24,-24 }},
		}
	obj = instance:createObject(level.layers['Layer1'],objProps, level.assets) 
	objProps = 
	{
		name 	= 'text', 
		objType = 'LDText',
		class = '',
		width	= 519,
		height	= 40,
		x		= 13,
		y		= 920,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		rotation	= 0,
		enableDrag	= false, 
		anchorX = 0,
		anchorY = 0,
		alpha = 1,
		isVisible = true,
		blendMode = 'normal',
		assetName	= '',
		textProps	= {text = 'Level Director X - Vector Example', font = 'Arial Black',size = 25, embossed = false,embossHighlightColorR = 255 / 255,embossHighlightColorG = 255 / 255,embossHighlightColorB = 255 / 255, embossHighlightColorA = 255 / 255,embossShadowColorR = 255 / 255,embossShadowColorG = 255 / 255,embossShadowColorB = 255 / 255, embossShadowColorA = 255 / 255},
		styleProps	= {radius = 259.5, cornerRadius = 0,strokeWidth = 1, strokeColorR = 255 / 255,strokeColorG = 255 / 255,strokeColorB = 255 / 255, strokeColorA = 255 / 255, fillColorR = 0 / 255, fillColorG = 0 / 255, fillColorB = 0 / 255, fillColorA = 0 / 255},
		fillProps = {fillType = 0, fillAssetName = '', fillFrame = 0 },
		gradientProps = {direction = 0, fillColorR = 0 / 255,fillColorG = 0 / 255,fillColorB = 0 / 255, fillColorA = 0 / 255},
		}
	obj = instance:createObject(level.layers['Layer1'],objProps, level.assets) 
	objProps = 
	{
		name 	= 'right_eye', 
		objType = 'LDEllipse',
		class = '',
		width	= 160,
		height	= 160,
		x		= 464,
		y		= 256,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		assetName	= '',
		styleProps	= {radius = 80, cornerRadius = 0,strokeWidth = 1, strokeColorR = 255 / 255,strokeColorG = 255 / 255,strokeColorB = 255 / 255, strokeColorA = 255 / 255, fillColorR = 0 / 255, fillColorG = 0 / 255, fillColorB = 0 / 255, fillColorA = 0 / 255},
		fillProps = {fillType = 0, fillAssetName = '', fillFrame = 0 },
		gradientProps = {direction = 0, fillColorR = 0 / 255,fillColorG = 0 / 255,fillColorB = 0 / 255, fillColorA = 0 / 255},
		}
	obj = instance:createObject(level.layers['Layer1'],objProps, level.assets) 
	objProps = 
	{
		name 	= 'nose', 
		objType = 'LDRectangle',
		class = '',
		width	= 32,
		height	= 96,
		x		= 320,
		y		= 416,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		assetName	= '',
		styleProps	= {radius = 16, cornerRadius = 0,strokeWidth = 1, strokeColorR = 255 / 255,strokeColorG = 255 / 255,strokeColorB = 255 / 255, strokeColorA = 255 / 255, fillColorR = 0 / 255, fillColorG = 0 / 255, fillColorB = 0 / 255, fillColorA = 0 / 255},
		fillProps = {fillType = 0, fillAssetName = '', fillFrame = 0 },
		gradientProps = {direction = 0, fillColorR = 0 / 255,fillColorG = 0 / 255,fillColorB = 0 / 255, fillColorA = 0 / 255},
		}
	obj = instance:createObject(level.layers['Layer1'],objProps, level.assets) 
	objProps = 
	{
		name 	= 'pout', 
		objType = 'LDPath',
		class = '',
		width	= 0,
		height	= 0,
		x		= 320,
		y		= 616,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		assetName	= '',
		styleProps	= {radius = 0, cornerRadius = 0,strokeWidth = 1, strokeColorR = 255 / 255,strokeColorG = 255 / 255,strokeColorB = 255 / 255, strokeColorA = 255 / 255, fillColorR = 0 / 255, fillColorG = 0 / 255, fillColorB = 0 / 255, fillColorA = 0 / 255},
		fillProps = {fillType = 0, fillAssetName = '', fillFrame = 0 },
		gradientProps = {direction = 0, fillColorR = 0 / 255,fillColorG = 0 / 255,fillColorB = 0 / 255, fillColorA = 0 / 255},
		pointProps = {outputType = 'Display', xPoints = {-256,256,256,-256}, yPoints = { -8,-8,8,8 }},
		}
	obj = instance:createObject(level.layers['Layer1'],objProps, level.assets) 
	objProps = 
	{
		name 	= 'left_eyeball', 
		objType = 'LDEllipse',
		class = '',
		width	= 32,
		height	= 32,
		x		= 176,
		y		= 256,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		assetName	= '',
		styleProps	= {radius = 16, cornerRadius = 0,strokeWidth = 1, strokeColorR = 255 / 255,strokeColorG = 255 / 255,strokeColorB = 255 / 255, strokeColorA = 255 / 255, fillColorR = 255 / 255, fillColorG = 255 / 255, fillColorB = 255 / 255, fillColorA = 255 / 255},
		fillProps = {fillType = 0, fillAssetName = '', fillFrame = 0 },
		gradientProps = {direction = 0, fillColorR = 255 / 255,fillColorG = 255 / 255,fillColorB = 255 / 255, fillColorA = 255 / 255},
		}
	obj = instance:createObject(level.layers['Layer1'],objProps, level.assets) 
	objProps = 
	{
		name 	= 'right_eyeball', 
		objType = 'LDEllipse',
		class = '',
		width	= 32,
		height	= 32,
		x		= 464,
		y		= 256,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		assetName	= '',
		styleProps	= {radius = 16, cornerRadius = 0,strokeWidth = 1, strokeColorR = 255 / 255,strokeColorG = 255 / 255,strokeColorB = 255 / 255, strokeColorA = 255 / 255, fillColorR = 255 / 255, fillColorG = 255 / 255, fillColorB = 255 / 255, fillColorA = 255 / 255},
		fillProps = {fillType = 0, fillAssetName = '', fillFrame = 0 },
		gradientProps = {direction = 0, fillColorR = 255 / 255,fillColorG = 255 / 255,fillColorB = 255 / 255, fillColorA = 255 / 255},
		}
	obj = instance:createObject(level.layers['Layer1'],objProps, level.assets) 
	objProps = 
	{
		name 	= 'right_eyebrow', 
		objType = 'LDPath',
		class = '',
		width	= 0,
		height	= 0,
		x		= 456,
		y		= 152,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		assetName	= '',
		styleProps	= {radius = 0, cornerRadius = 0,strokeWidth = 1, strokeColorR = 255 / 255,strokeColorG = 255 / 255,strokeColorB = 255 / 255, strokeColorA = 255 / 255, fillColorR = 0 / 255, fillColorG = 0 / 255, fillColorB = 0 / 255, fillColorA = 0 / 255},
		fillProps = {fillType = 0, fillAssetName = '', fillFrame = 0 },
		gradientProps = {direction = 0, fillColorR = 0 / 255,fillColorG = 0 / 255,fillColorB = 0 / 255, fillColorA = 0 / 255},
		pointProps = {outputType = 'Display', xPoints = {-88,-40,88}, yPoints = { 24,-24,-24 }},
		}
	obj = instance:createObject(level.layers['Layer1'],objProps, level.assets) 
	objProps = 
	{
		name 	= 'left_eyebrow', 
		objType = 'LDPath',
		class = '',
		width	= 0,
		height	= 0,
		x		= 176,
		y		= 152,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		assetName	= '',
		styleProps	= {radius = 0, cornerRadius = 0,strokeWidth = 1, strokeColorR = 255 / 255,strokeColorG = 255 / 255,strokeColorB = 255 / 255, strokeColorA = 255 / 255, fillColorR = 0 / 255, fillColorG = 0 / 255, fillColorB = 0 / 255, fillColorA = 0 / 255},
		fillProps = {fillType = 0, fillAssetName = '', fillFrame = 0 },
		gradientProps = {direction = 0, fillColorR = 0 / 255,fillColorG = 0 / 255,fillColorB = 0 / 255, fillColorA = 0 / 255},
		pointProps = {outputType = 'Display', xPoints = {80,32,-80}, yPoints = { 24,-24,-24 }},
		}
	obj = instance:createObject(level.layers['Layer1'],objProps, level.assets) 
	instance:insertLayer(level,level.layers['Layer1'])
	--level.ldVersion = 1.0.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth = 640
	level.canvasHeight = 960
	if level.parallaxEnabled then
		level.parallaxInfinite = false
		level.parallaxDamping = 1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

