-- Generated by Level Director X v1.0.0 on Sun Aug 2 18:31:51 2015 --
require("lib.LD_HelperX")
local M = {}
-----------------------------------
function M:loadAssets()
-----------------------------------
	local assets = {}
	assets.spriteSheetData = {}
	assets.spriteSheetData['player'] = {}
	assets.spriteSheetData['player'].frames ={
		{ 	-- player_0 --
			x = 0,
			y = 0,
			width = 48,
			height = 48
		},
		{ 	-- player_1 --
			x = 48,
			y = 0,
			width = 48,
			height = 48
		},
		{ 	-- player_2 --
			x = 96,
			y = 0,
			width = 48,
			height = 48
		},
		{ 	-- player_3 --
			x = 144,
			y = 0,
			width = 48,
			height = 48
		},
		{ 	-- player_4 --
			x = 0,
			y = 48,
			width = 48,
			height = 48
		},
		{ 	-- player_5 --
			x = 48,
			y = 48,
			width = 48,
			height = 48
		},
		{ 	-- player_6 --
			x = 96,
			y = 48,
			width = 48,
			height = 48
		},
		{ 	-- player_7 --
			x = 144,
			y = 48,
			width = 48,
			height = 48
		},
		{ 	-- player_8 --
			x = 0,
			y = 96,
			width = 48,
			height = 48
		},
		{ 	-- player_9 --
			x = 48,
			y = 96,
			width = 48,
			height = 48
		},
		{ 	-- player_10 --
			x = 96,
			y = 96,
			width = 48,
			height = 48
		},
		{ 	-- player_11 --
			x = 144,
			y = 96,
			width = 48,
			height = 48
		},
		{ 	-- player_12 --
			x = 0,
			y = 144,
			width = 48,
			height = 48
		},
		{ 	-- player_13 --
			x = 48,
			y = 144,
			width = 48,
			height = 48
		},
		{ 	-- player_14 --
			x = 96,
			y = 144,
			width = 48,
			height = 48
		},
		{ 	-- player_15 --
			x = 144,
			y = 144,
			width = 48,
			height = 48
		},
		sheetContentWidth = 192,
		sheetContentHeight = 192
	}
	assets.spriteSheetData['greenman'] = {}
	assets.spriteSheetData['greenman'].frames ={
		{ 	-- greenman_0 --
			x = 0,
			y = 0,
			width = 128,
			height = 128
		},
		{ 	-- greenman_1 --
			x = 128,
			y = 0,
			width = 128,
			height = 128
		},
		{ 	-- greenman_2 --
			x = 256,
			y = 0,
			width = 128,
			height = 128
		},
		{ 	-- greenman_3 --
			x = 384,
			y = 0,
			width = 128,
			height = 128
		},
		{ 	-- greenman_4 --
			x = 0,
			y = 128,
			width = 128,
			height = 128
		},
		{ 	-- greenman_5 --
			x = 128,
			y = 128,
			width = 128,
			height = 128
		},
		{ 	-- greenman_6 --
			x = 256,
			y = 128,
			width = 128,
			height = 128
		},
		{ 	-- greenman_7 --
			x = 384,
			y = 128,
			width = 128,
			height = 128
		},
		{ 	-- greenman_8 --
			x = 0,
			y = 256,
			width = 128,
			height = 128
		},
		{ 	-- greenman_9 --
			x = 128,
			y = 256,
			width = 128,
			height = 128
		},
		{ 	-- greenman_10 --
			x = 256,
			y = 256,
			width = 128,
			height = 128
		},
		{ 	-- greenman_11 --
			x = 384,
			y = 256,
			width = 128,
			height = 128
		},
		{ 	-- greenman_12 --
			x = 0,
			y = 384,
			width = 128,
			height = 128
		},
		{ 	-- greenman_13 --
			x = 128,
			y = 384,
			width = 128,
			height = 128
		},
		{ 	-- greenman_14 --
			x = 256,
			y = 384,
			width = 128,
			height = 128
		},
		{ 	-- greenman_15 --
			x = 384,
			y = 384,
			width = 128,
			height = 128
		},
		sheetContentWidth = 512,
		sheetContentHeight = 512
	}
	assets['player_0']={
		file = 'player.png',
		name = 'player_0',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 48,
		height = 48,
		frame = 1,
		spriteSheetName = 'player',
		frameCount = 16,		
		sequenceData = {
		{ name='down', frames = { 1,5,9,13 }, time = 500, loopCount = 0, loopDirection = 'forward' },
		{ name='left', frames = { 2,6,10,14 }, time = 500, loopCount = 0, loopDirection = 'forward' },
		{ name='up', frames = { 3,7,11,15 }, time = 500, loopCount = 0, loopDirection = 'forward' },
		{ name='right', frames = { 4,8,12,16 }, time = 500, loopCount = 0, loopDirection = 'forward' },
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = true, 
						source = 'Asset',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = false,
						isSensor = false,
						isBullet = false,
						shapes = {						
							{bodyShape = 'Round',
							shape     = {},
							bounce    = 0.2,
							friction  = 0.3,
							density   = 1,
							radius    = 18,
							categoryBits = 0,
							maskBits  = 0,
							groupIndex = 0},
						}
					}
	}	
	assets['player_1']={
		file = 'player.png',
		name = 'player_1',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 48,
		height = 48,
		frame = 2,
		spriteSheetName = 'player',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['player_2']={
		file = 'player.png',
		name = 'player_2',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 48,
		height = 48,
		frame = 3,
		spriteSheetName = 'player',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['player_3']={
		file = 'player.png',
		name = 'player_3',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 48,
		height = 48,
		frame = 4,
		spriteSheetName = 'player',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['player_4']={
		file = 'player.png',
		name = 'player_4',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 48,
		height = 48,
		frame = 5,
		spriteSheetName = 'player',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['player_5']={
		file = 'player.png',
		name = 'player_5',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 48,
		height = 48,
		frame = 6,
		spriteSheetName = 'player',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['player_6']={
		file = 'player.png',
		name = 'player_6',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 48,
		height = 48,
		frame = 7,
		spriteSheetName = 'player',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['player_7']={
		file = 'player.png',
		name = 'player_7',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 48,
		height = 48,
		frame = 8,
		spriteSheetName = 'player',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['player_8']={
		file = 'player.png',
		name = 'player_8',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 48,
		height = 48,
		frame = 9,
		spriteSheetName = 'player',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['player_9']={
		file = 'player.png',
		name = 'player_9',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 48,
		height = 48,
		frame = 10,
		spriteSheetName = 'player',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['player_10']={
		file = 'player.png',
		name = 'player_10',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 48,
		height = 48,
		frame = 11,
		spriteSheetName = 'player',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['player_11']={
		file = 'player.png',
		name = 'player_11',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 48,
		height = 48,
		frame = 12,
		spriteSheetName = 'player',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['player_12']={
		file = 'player.png',
		name = 'player_12',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 48,
		height = 48,
		frame = 13,
		spriteSheetName = 'player',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['player_13']={
		file = 'player.png',
		name = 'player_13',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 48,
		height = 48,
		frame = 14,
		spriteSheetName = 'player',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['player_14']={
		file = 'player.png',
		name = 'player_14',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 48,
		height = 48,
		frame = 15,
		spriteSheetName = 'player',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['player_15']={
		file = 'player.png',
		name = 'player_15',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 48,
		height = 48,
		frame = 16,
		spriteSheetName = 'player',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['sky_0']={
		file = 'sky.jpg',
		name = 'sky_0',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 480,
		height = 320,
		frame = 0,
		spriteSheetName = 'sky',
		frameCount = 1,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['greenman_0']={
		file = 'greenman.png',
		name = 'greenman_0',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 128,
		height = 128,
		frame = 1,
		spriteSheetName = 'greenman',
		frameCount = 16,		
		sequenceData = {
		{ name='run', frames = { 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 }, time = 500, loopCount = 0, loopDirection = 'forward' },
		},
		sequenceInfo = {default = 'run', play= true },
		physics	= 	{	isEnabled = true, 
						source = 'Asset',
						bodyType  = 'dynamic',
						isFixedRotation = false,
						isSleepingAllowed = false,
						isSensor = false,
						isBullet = false,
						shapes = {
						}
					}
	}	
	assets['greenman_1']={
		file = 'greenman.png',
		name = 'greenman_1',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 128,
		height = 128,
		frame = 2,
		spriteSheetName = 'greenman',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['greenman_2']={
		file = 'greenman.png',
		name = 'greenman_2',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 128,
		height = 128,
		frame = 3,
		spriteSheetName = 'greenman',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['greenman_3']={
		file = 'greenman.png',
		name = 'greenman_3',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 128,
		height = 128,
		frame = 4,
		spriteSheetName = 'greenman',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['greenman_4']={
		file = 'greenman.png',
		name = 'greenman_4',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 128,
		height = 128,
		frame = 5,
		spriteSheetName = 'greenman',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['greenman_5']={
		file = 'greenman.png',
		name = 'greenman_5',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 128,
		height = 128,
		frame = 6,
		spriteSheetName = 'greenman',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['greenman_6']={
		file = 'greenman.png',
		name = 'greenman_6',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 128,
		height = 128,
		frame = 7,
		spriteSheetName = 'greenman',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['greenman_7']={
		file = 'greenman.png',
		name = 'greenman_7',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 128,
		height = 128,
		frame = 8,
		spriteSheetName = 'greenman',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['greenman_8']={
		file = 'greenman.png',
		name = 'greenman_8',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 128,
		height = 128,
		frame = 9,
		spriteSheetName = 'greenman',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['greenman_9']={
		file = 'greenman.png',
		name = 'greenman_9',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 128,
		height = 128,
		frame = 10,
		spriteSheetName = 'greenman',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['greenman_10']={
		file = 'greenman.png',
		name = 'greenman_10',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 128,
		height = 128,
		frame = 11,
		spriteSheetName = 'greenman',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['greenman_11']={
		file = 'greenman.png',
		name = 'greenman_11',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 128,
		height = 128,
		frame = 12,
		spriteSheetName = 'greenman',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['greenman_12']={
		file = 'greenman.png',
		name = 'greenman_12',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 128,
		height = 128,
		frame = 13,
		spriteSheetName = 'greenman',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['greenman_13']={
		file = 'greenman.png',
		name = 'greenman_13',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 128,
		height = 128,
		frame = 14,
		spriteSheetName = 'greenman',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['greenman_14']={
		file = 'greenman.png',
		name = 'greenman_14',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 128,
		height = 128,
		frame = 15,
		spriteSheetName = 'greenman',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['greenman_15']={
		file = 'greenman.png',
		name = 'greenman_15',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 128,
		height = 128,
		frame = 16,
		spriteSheetName = 'greenman',
		frameCount = 16,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	assets['grass_0']={
		file = 'grass.png',
		name = 'grass_0',
		class = '',
		anchorX = 0.5,
		anchorY = 0.5,
		width = 480,
		height = 40,
		frame = 0,
		spriteSheetName = 'grass',
		frameCount = 1,		
		sequenceData = {
		},
		sequenceInfo = {default = '', play= false },
		physics	= 	{	isEnabled = false, 
					}
	}	
	return assets
end -- loadAssets 

------------------------------------------
function M:createLevel(LD_Helper_Instance)
------------------------------------------
	local instance = LD_Helper_Instance
	local objProps = {}
	local level = {}
    local obj = nil
	if (application.LevelDirectorSettings.viewGroup == nil) then
		level.view = display.newGroup() 
	else
		level.view = application.LevelDirectorSettings.viewGroup
	end
	level.view.anchorChildren =false 
	display.setDefault( 'background',  102 / 255, 102 / 255, 102 / 255, 255 / 255)
	display.setDefault( "anchorX", 0.5 )
	display.setDefault( "anchorY", 0.5 )	
	display.setDrawMode("wireframe",false)
	level.name = 'level01' 
	-- Load Assets
	level.assets = self:loadAssets()
	-- Physics properties
	physics.setGravity(0,9.8) 
	physics.setDrawMode('hybrid')
	physics.setPositionIterations(8)	
	physics.setVelocityIterations(3)	
	level.parallaxEnabled = false
	level.Enemy = ''
	-- Layers --
	level.layers = {} 
	---- bg ------------------------------------------------------------------------------------
	level.layers['bg'] = {} 
	level.layers['bg'].view = display.newGroup() 
	level.layers['bg'].name = 'bg' 
	if (level.parallaxEnabled) then
		level.layers['bg'].speed = {x = 0, y = 0}
		level.layers['bg'].repeated = false
		level.layers['bg'].cullingMethod = 0
	else
		level.layers['bg'].cullingMethod = 0 
	end
	level.layers['bg'].objects = {} 
	objProps = 
	{
		name 	= 'sky', 
		objType = 'LDImage',
		class = '',
		width	= 960,
		height	= 640,
		x		= 480,
		y		= 320,
		xScale		= 2 * 1,
		yScale		= 2 * 1,
		assetName	= 'sky_0',
		}
	obj = instance:createObject(level.layers['bg'],objProps, level.assets) 
	instance:insertLayer(level,level.layers['bg'])
	---- fg ------------------------------------------------------------------------------------
	level.layers['fg'] = {} 
	level.layers['fg'].view = display.newGroup() 
	level.layers['fg'].name = 'fg' 
	if (level.parallaxEnabled) then
		level.layers['fg'].speed = {x = 0, y = 0}
		level.layers['fg'].repeated = false
		level.layers['fg'].cullingMethod = 0
	else
		level.layers['fg'].cullingMethod = 0 
	end
	level.layers['fg'].objects = {} 
	objProps = 
	{
		name 	= 'asset_2', 
		objType = 'LDImage',
		class = '',
		width	= 480,
		height	= 40,
		x		= 240,
		y		= 628,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		assetName	= 'grass_0',
		}
	obj = instance:createObject(level.layers['fg'],objProps, level.assets) 
	objProps = 
	{
		name 	= 'asset_3', 
		objType = 'LDImage',
		class = '',
		width	= 480,
		height	= 40,
		x		= 720,
		y		= 628,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		assetName	= 'grass_0',
		}
	obj = instance:createObject(level.layers['fg'],objProps, level.assets) 
	objProps = 
	{
		name 	= 'rect_3', 
		objType = 'LDRectangle',
		class = '',
		width	= 960,
		height	= 32,
		x		= 480,
		y		= 656,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		assetName	= '',
		styleProps	= {radius = 480, cornerRadius = 0,strokeWidth = 1, strokeColorR = 255 / 255,strokeColorG = 255 / 255,strokeColorB = 255 / 255, strokeColorA = 255 / 255, fillColorR = 0 / 255, fillColorG = 0 / 255, fillColorB = 0 / 255, fillColorA = 0 / 255},
		fillProps = {fillType = 0, fillAssetName = '', fillFrame = 0 },
		gradientProps = {direction = 0, fillColorR = 0 / 255,fillColorG = 0 / 255,fillColorB = 0 / 255, fillColorA = 0 / 255},
		physics	= 	{	isEnabled = true, source = 'Object',
						bodyType  = 'static',
						isFixedRotation = false,
						isSleepingAllowed = false,
						isSensor = false,
						isBullet = false,
						gravityScale = 1,
						shapes = {
							{bodyShape = 'Rectangle',
							shape     = { },
							bounce    = 0.2,
							friction  = 0.3,
							density   = 1,
							radius    = 0,
							categoryBits = 0,
							maskBits  = 0,
							groupIndex = 0 },
						}
					}
		}
	obj = instance:createObject(level.layers['fg'],objProps, level.assets) 
	objProps = 
	{
		name 	= 'asset_4', 
		objType = 'LDImage',
		class = '',
		width	= 128,
		height	= 128,
		x		= 160,
		y		= 512,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		assetName	= 'greenman_0',
		}
	obj = instance:createObject(level.layers['fg'],objProps, level.assets) 
	instance:insertLayer(level,level.layers['fg'])
	---- hud ------------------------------------------------------------------------------------
	level.layers['hud'] = {} 
	level.layers['hud'].view = display.newGroup() 
	level.layers['hud'].name = 'hud' 
	if (level.parallaxEnabled) then
		level.layers['hud'].speed = {x = 0, y = 0}
		level.layers['hud'].repeated = false
		level.layers['hud'].cullingMethod = 0
	else
		level.layers['hud'].cullingMethod = 0 
	end
	level.layers['hud'].objects = {} 
	objProps = 
	{
		name 	= 'title', 
		objType = 'LDText',
		class = '',
		width	= 444,
		height	= 38,
		x		= 10,
		y		= 608,
		xScale		= 1 * 1,
		yScale		= 1 * 1,
		rotation	= 0,
		enableDrag	= false, 
		anchorX = 0,
		anchorY = 0,
		alpha = 1,
		isVisible = true,
		blendMode = 'normal',
		assetName	= '',
		textProps	= {text = 'Level Director X - Asset Demo', font = 'Arial Black',size = 24, embossed = false,embossHighlightColorR = 255 / 255,embossHighlightColorG = 255 / 255,embossHighlightColorB = 255 / 255, embossHighlightColorA = 255 / 255,embossShadowColorR = 255 / 255,embossShadowColorG = 255 / 255,embossShadowColorB = 255 / 255, embossShadowColorA = 255 / 255},
		styleProps	= {radius = 222, cornerRadius = 0,strokeWidth = 1, strokeColorR = 255 / 255,strokeColorG = 255 / 255,strokeColorB = 255 / 255, strokeColorA = 255 / 255, fillColorR = 0 / 255, fillColorG = 0 / 255, fillColorB = 0 / 255, fillColorA = 0 / 255},
		fillProps = {fillType = 0, fillAssetName = '', fillFrame = 0 },
		gradientProps = {direction = 0, fillColorR = 0 / 255,fillColorG = 0 / 255,fillColorB = 0 / 255, fillColorA = 0 / 255},
		}
	obj = instance:createObject(level.layers['hud'],objProps, level.assets) 
	instance:insertLayer(level,level.layers['hud'])
	--level.ldVersion = 1.0.0	-- Level Director Version
	-- Parallax (after layers)
	level.canvasWidth = 960
	level.canvasHeight = 640
	if level.parallaxEnabled then
		level.parallaxInfinite = false
		level.parallaxDamping = 1
		instance:createParallax(level)
	end
	return level
end -- createLevel
return M

